### ISSUE TITLE
Domain arry issue

### ISSUE THREAD

**Issue by deviljutt** [shariqmalik/AdminBuster#1]
Hi,
I have tested this script it was work fine but now i am geting error could you please help me into it,

 -http://prntscr.com/ka84jc

**Comment by shariqmalik** [comment]
@deviljutt first of all thanks for reporting that issue. Its due to an API fail. I'm working on it I'll resolve it asap.

**Comment by shariqmalik** [comment]
@deviljutt your issue is resolved. The issue was with SSL you can get update script now.
![screenshot from 2018-07-26 10-11-53](https://user-images.githubusercontent.com/19536819/43242840-b7f03a2c-90bc-11e8-86db-4f46d5916e63.png)
results after updating :+1:
